name = "QNMSpectralSolve"
uuid = "25095b70-8a02-4423-a837-b91b6f8f239c"
authors = ["Asad Hussain <asadh@utexas.edu>"]
version = "0.1.0"

[deps]
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
